### ISSUE TITLE
Pipelines tasks refer to virtmerlin/c0-worker, c0 team dockerhub may be better?

### ISSUE THREAD

**Issue by bijukunjummen** [pivotal-cf/aws-concourse#12]
I noticed that some of the pipeline steps refer to this docker image `virtmerlin/c0-worker`, wouldn't hosting and using docker images from a team dockerhub a better idea.

**Comment by krishicks** [comment]
We have chores to replace any non-cflinuxfs2 images with either cflinuxfs2 or one based on cflinuxfs2 that we maintain.

They're here:

https://www.pivotaltracker.com/story/show/144251129
https://www.pivotaltracker.com/story/show/144251109
https://www.pivotaltracker.com/story/show/144251095
