### ISSUE TITLE
OPSMAN_URI parameter likely redundant

### ISSUE THREAD

**Issue by bijukunjummen** [pivotal-cf/aws-concourse#13]
The `OPSMAN_URI` parameter is likely to be redundant - in some of the pipeline steps it is derived as `https://opsman.$ERT_DOMAIN`, if by any chance a different `OPSMAN_URI` is provided the import-stemcell step fails as the url's don't match up. We should either use `OPSMAN_URI` at all places or remove `OPSMAN_URI` and derive the url.

**Comment by ryanpei** [comment]
@bijukunjummen so we would replace `OPSMAN_URI` with `ERT_DOMAIN` in all places where it is currently used?

**Comment by bijukunjummen** [comment]
Yes, I think so @ryanpei, OR make use of the `OPSMAN_URI` everywhere a opsman's url is required instead of deriving it as `https://opsman.$ERT_DOMAIN`. Former may be a good start though.

**Comment by ryanpei** [comment]
cool, I will close this issue in preference for the `pcf-pipelines` one since we moved our workloads there.

@krishicks should we just deprecate this repo in favor of what we now have in `pcf-pipelines`?
