### ISSUE TITLE
Opsman should be associated with an elastic ip address

### ISSUE THREAD

**Issue by bijukunjummen** [pivotal-cf/aws-concourse#14]
The terraform scripts for provisioning an opsman vm should associate an elastic ip address with the opsman vm, otherwise the upgrade scripts for opsman tends to fail as it tries to associate the non-elastic ip to the new instance and fails.

**Comment by krishicks** [comment]
Closing this in favor of https://github.com/pivotal-cf/pcf-pipelines/issues/51, as this repo is now deprecated.
