### ISSUE TITLE
params.yml.sample versus terraform/variables.tf

### ISSUE THREAD

**Issue by akumria** [pivotal-cf/aws-concourse#7]
Hi,

What is the rationale for having different values for AWS resources specified in `params.yml.sample` and then various defaults in `terraform/variables.tf`.

Thanks,
Anand

**Comment by akumria** [comment]
Note the discrepancy means that the `readme.md` refers to `IP_PREFIX` which doesn't exist (but that references the CIDR space mentioned in `terraform/variables.tf`

**Comment by krishicks** [comment]
This is something we should fix by having a single place for defaults. The README should also be overhauled, perhaps in concert with an overhaul of the rest of the repo.

**Comment by akumria** [comment]
As this repository is now deprecated, this can be fixed in https://github.com/pivotal-cf/pcf-pipelines instead.
