### ISSUE TITLE
why a fork of om

### ISSUE THREAD

**Issue by wjk940** [pivotal-cf/aws-concourse#8]
https://github.com/c0-ops/om (0.8.1) https://github.com/pivotal-cf/om/releases (0.22.0) — I don’t know why the script isn’t using `om [options] configure-bosh [<args>]`

**Comment by ryanpei** [comment]
this is a good point. we should refactor the pipelines to use `om configure-bosh` now that this is supported in `om` master.

**Comment by ryanpei** [comment]
closing this in favor of https://github.com/pivotal-cf/pcf-pipelines/issues/67
